// Generated by ReScript (stub for testing without rescript installed)
// Analytics module

const analytics = {
  totalVisits: 0,
  styleViews: {},
  errorCodeViews: {},
  customMessages: 0,
  apiCalls: 0,
  startTime: Date.now(),
};

function incrementDict(dict, key) {
  dict[key] = (dict[key] || 0) + 1;
}

function trackVisit(style, errorCode, isCustom) {
  analytics.totalVisits++;
  incrementDict(analytics.styleViews, style);
  incrementDict(analytics.errorCodeViews, errorCode);

  if (isCustom) {
    analytics.customMessages++;
  }
}

function trackApiCall() {
  analytics.apiCalls++;
}

function getStats() {
  return analytics;
}

function getUptime() {
  return (Date.now() - analytics.startTime) / 1000;
}

function resetStats() {
  analytics.totalVisits = 0;
  analytics.styleViews = {};
  analytics.errorCodeViews = {};
  analytics.customMessages = 0;
  analytics.apiCalls = 0;
}

function getStatsObject() {
  return {
    totalVisits: analytics.totalVisits,
    styleViews: analytics.styleViews,
    errorCodeViews: analytics.errorCodeViews,
    customMessages: analytics.customMessages,
    apiCalls: analytics.apiCalls,
    uptime: getUptime(),
  };
}

export { trackVisit, trackApiCall, getStats, getUptime, resetStats, getStatsObject };
