// Generated by ReScript (stub for testing without rescript installed)
// ErrorMessages module

const stopCodes = [
  "CRITICAL_PROCESS_DIED",
  "SYSTEM_SERVICE_EXCEPTION",
  "PAGE_FAULT_IN_NONPAGED_AREA",
  "COFFEE_NOT_FOUND",
  "PRODUCTION_DEPLOYMENT_ON_FRIDAY",
  "NPM_INSTALL_TIMEOUT",
  "STACKOVERFLOW_COPY_PASTE_ERROR",
  "MERGE_CONFLICT_ANXIETY",
  "UNDEFINED_IS_NOT_A_FUNCTION",
  "CIRCULAR_DEPENDENCY_LOOP",
];

const descriptions = {
  "CRITICAL_PROCESS_DIED": "Your PC ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.",
  "COFFEE_NOT_FOUND": "Critical system resource COFFEE.SYS not found. Please insert coffee and press any key to continue.",
  "PRODUCTION_DEPLOYMENT_ON_FRIDAY": "CRITICAL ERROR: Someone tried to deploy to production on Friday at 4:45 PM.",
  "NPM_INSTALL_TIMEOUT": "npm install has been running for 3 hours. Heat death of universe expected before completion.",
  "STACKOVERFLOW_COPY_PASTE_ERROR": "Code copied from StackOverflow contained malicious solutions. Surprising absolutely no one.",
  "MERGE_CONFLICT_ANXIETY": "Unresolved merge conflicts detected. Developer anxiety levels critical.",
  "UNDEFINED_IS_NOT_A_FUNCTION": "TypeError: undefined is not a function. But then again, what even is?",
  "CIRCULAR_DEPENDENCY_LOOP": "Circular dependency detected. Like your thoughts at 3 AM.",
};

const technicalDetails = [
  "Failed driver: SARCASM.SYS",
  "Failed driver: PROCRASTINATION.DLL",
  "Failed driver: CAFFEINE.DLL",
  "Memory dump: 0xC0FFEE",
  "Memory dump: 0xDEADBEEF",
  "Memory dump: 0xBADC0DE",
  "Error code: 418 (I'm a teapot)",
  "Error code: 404 (Motivation not found)",
];

const qrMessages = [
  "Scan for totally legitimate Windows support",
  "Scan for cat pictures",
  "Scan for emotional support",
  "Scan for the meaning of life",
];

function randomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomErrorJS() {
  const stopCode = randomElement(stopCodes);
  const description = descriptions[stopCode] || descriptions["CRITICAL_PROCESS_DIED"];
  const technicalDetail = randomElement(technicalDetails);
  const qrMessage = randomElement(qrMessages);
  const percentage = Math.floor(Math.random() * 101);

  return {
    stopCode,
    description,
    technicalDetail,
    qrMessage,
    percentage,
  };
}

function getErrorByCodeJS(code) {
  const normalizedCode = code.toUpperCase().replace(/-/g, "_");

  if (!stopCodes.includes(normalizedCode)) {
    return null;
  }

  const description = descriptions[normalizedCode] || descriptions["CRITICAL_PROCESS_DIED"];
  const technicalDetail = randomElement(technicalDetails);
  const qrMessage = randomElement(qrMessages);
  const percentage = Math.floor(Math.random() * 101);

  return {
    stopCode: normalizedCode,
    description,
    technicalDetail,
    qrMessage,
    percentage,
  };
}

function getAllStopCodes() {
  return stopCodes;
}

export { getRandomErrorJS, getErrorByCodeJS, getAllStopCodes };
